#!/usr/bin/env bash
# This is a script from 1 to 20 with loops and breaks

count=1

while [ $count -le 20 ]
do
      echo "$count"
      case $count in
              "4") echo "bad luck from China";;
              "9") echo "bad luck from Japan";;
              "17") echo "bad luck from Italy";;
      esac
      (( count++ ))
done      